name: release

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 检出代码

      - name: install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable  # 使用稳定版 Rust

      - name: build Release version
        run: cargo build --release  # 编译发布版

      - name: Release
        uses: softprops/action-gh-release@v1  # 使用新版发布工具
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的令牌
        with:
          tag_name: ${{ github.ref_name }}  # 使用触发工作流的标签名
          name: build ${{ github.ref_name }}  # 发布标题
          files: |  # 要上传的发布文件
            target/release/alt-create